# Generated by Django 4.1.3 on 2023-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imprisoned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('article', models.CharField(max_length=30, verbose_name='Статья')),
                ('time_start', models.DateTimeField(verbose_name='Начало срока')),
                ('period', models.CharField(max_length=30, verbose_name='Срок')),
                ('block', models.CharField(max_length=30, verbose_name='Номер блока')),
                ('cell', models.CharField(max_length=30, verbose_name='Номер камеры')),
                ('note_about_behavior', models.TextField(verbose_name='Примечание о поведении')),
            ],
        ),
    ]
