# Generated by Django 4.1.3 on 2023-02-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imprisoned',
            options={'verbose_name': 'Заключенный', 'verbose_name_plural': 'Заключенные'},
        ),
    ]
